### ISSUE TITLE
IndexOutOfBoundsException when Identity prop value is empty String

### ISSUE THREAD

**Issue by golszewski86** [yegor256/takes#1021]
The following code:

```java
final Request req = new RqWithAuth(
    new Identity.Simple("urn", new MapOf<>(new MapEntry<>("key", "")))
);
final Identity identity = new RqAuth(req).identity();
```

Produces exception:

```text
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
	at org.cactoos.list.ListEnvelope.get(ListEnvelope.java:86)
	at org.takes.facets.auth.codecs.CcPlain.decode(CcPlain.java:83)
	at org.takes.facets.auth.RqAuth.identity(RqAuth.java:78)
```
takes 1.19

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/1021#issuecomment-578965588))

@paulodamaso Thanks for your contribution, @golszewski86[/z](https://www.0crat.com/u/golszewski86)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by baudoliver7** [comment]
@0crat status

**Comment by baudoliver7** [comment]
@0crat status
