### ISSUE TITLE
PsBasic throws java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter on JDK 13

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#1048]
`PsBasic` class unable to load `DatatypeConverter` class on JDK 13 since it was excluded from default package in JDK 9. When trying to use `PsBasic` takes throws an exception:
```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.takes.facets.auth.PsBasic.enter(PsBasic.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:83)
	at org.takes.facets.forward.TkForward.act(TkForward.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.http.BkBasic.print(BkBasic.java:127)
	at org.takes.http.BkBasic.accept(BkBasic.java:103)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:49)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 13 more
```

Consider using another class for parsing bas64 encoded data.

---

Workaround: add these dependencies to classpath:
```xml
<dependency>
  <groupId>javax.xml.bind</groupId>
  <artifactId>jaxb-api</artifactId>
  <version>2.3.0</version>
</dependency>
<dependency>
  <groupId>com.sun.xml.bind</groupId>
  <artifactId>jaxb-core</artifactId>
  <version>2.3.0</version>
</dependency>
<dependency>
  <groupId>com.sun.xml.bind</groupId>
  <artifactId>jaxb-impl</artifactId>
  <version>2.3.0</version>
</dependency>
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by yegor256** [comment]
Fixed: `PsBasic` imports `jakarta.xml.bind.DatatypeConverter` and `jakarta.xml.bind-api` is a declared dependency, so it loads on JDK 9+.
