### ISSUE TITLE
Invalid HTTP method: X-Takes-LocalAddress

### ISSUE THREAD

**Issue by baudoliver7** [yegor256/takes#1227]
I got this error sometimes with the current version of Takes :

```console
java.io.IOException: Invalid HTTP method: X-Takes-LocalAddress:
	at org.takes.rq.RqMethod$Base.method(RqMethod.java:124)
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.fallback(TkFallback.java:138)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:88)
	at org.takes.facets.fallback.TkFallback.lambda$new$0(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkSlf4j.act(TkSlf4j.java:110)
	at org.takes.http.FtCli.lambda$start$0(FtCli.java:91)
	at org.takes.http.BkBasic.print(BkBasic.java:123)
	at org.takes.http.BkBasic.accept(BkBasic.java:99)
	at org.takes.http.BkSafe.lambda$new$0(BkSafe.java:46)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:92)
	at org.takes.http.BkParallel.lambda$new$0(BkParallel.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

While debugging, we got this:
![image](https://github.com/yegor256/takes/assets/7813046/c7be092f-0ed0-4945-8783-38f651eb5fc5)

It looks like `RqRequestLine.Base` doesn't do the right job :-(

**Comment by baudoliver7** [comment]
@yegor256 Do you have any idea of this error ?

**Comment by yegor256** [comment]
@baudoliver7 do you know how can I reproduce it?

**Comment by baudoliver7** [comment]
@yegor256 It is a bit difficult to reproduce it. It generally happens when I query a GET method on my local machine. It doesn't happen on a distant server.

**Comment by EugenDueck** [comment]
We are probably encountering the same thing in production for a couple of identical POST requests done every day. In those cases, `(new Base(req)).method()` is "OST", rather than "POST", so the first byte disappears somewhere.
I was able to replicate the problem locally by hammering the service using curl in an infinite loop:
- it happens after a couple hundred to a few tens of thousands of requests
- so far, I could only replicate it on Windows (not on Mac and not on Linux, doing > 200k tries each)
- it replicated on all JVMs I tried: OpenJDK 17.0.1 and OpenJDK 11.0.12

Example stack trace:
```
java.io.IOException: Invalid HTTP method: X-Takes-LocalAddress:
        at org.takes.rq.RqMethod$Base.method(RqMethod.java:124)
        at org.takes.facets.fallback.TkFallback.error(TkFallback.java:239)
        at org.takes.facets.fallback.TkFallback.fallback(TkFallback.java:143)
        at org.takes.facets.fallback.TkFallback.route(TkFallback.java:93)
        at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:57)
        at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:69)
        at org.takes.tk.TkWrap.act(TkWrap.java:58)
        at org.takes.http.BkBasic.print(BkBasic.java:127)
        at org.takes.http.BkBasic.accept(BkBasic.java:103)
        at org.takes.http.BkSafe$1.accept(BkSafe.java:49)
        at org.takes.http.BkWrap.accept(BkWrap.java:51)
        at org.takes.http.FtBasic.loop(FtBasic.java:114)
        at org.takes.http.FtBasic.start(FtBasic.java:100)
```

**Comment by EugenDueck** [comment]
I've stripped the problem down a bit further, while still being able to reproduce the above stack trace.
When I remove the TkFallback, I still get an exception after attempting a sufficient number of requests, so I believe it is due to the same root cause, even though the exception in that case is:
```
org.takes.HttpException: 404
        at org.takes.facets.fork.TkFork.act(TkFork.java:104)
        at org.takes.http.BkBasic.print(BkBasic.java:127)
        at org.takes.http.BkBasic.accept(BkBasic.java:103)
        at org.takes.http.BkSafe$1.accept(BkSafe.java:49)
        at org.takes.http.BkWrap.accept(BkWrap.java:51)
        at org.takes.http.FtBasic.loop(FtBasic.java:114)
        at org.takes.http.FtBasic.start(FtBasic.java:100)
```
This is the code that reproduces the above error, and the takes version is 1.19:
```java
public class Main {
    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("HH:mm:ss.SSS");
    private static volatile long lastLogTime = System.nanoTime();
    private static final AtomicLong postCount = new AtomicLong(0);
    private static final Collection<Fork> CONTROLLERS = List.of(
            new FkRegex("/a", new TkFork(new FkMethods("POST", req -> {
                long now = System.nanoTime();
                long postCount = Main.postCount.incrementAndGet();
                if (now - lastLogTime > 1_000_000_000) {
                    System.out.println(LocalTime.now().format(FORMATTER) + " " + postCount + " POST requests");
                    lastLogTime = now;
                }
                return new RsText("ok");
            })))
    );

    public static void main(String[] args) throws IOException {
        new FtBasic(new TkFork(CONTROLLERS), 8100).start(Exit.NEVER);
    }

}
```
The curl command I use (fish shell) is this:
```fish
while curl --fail-with-body -sX POST 'http://192.168.1.21:8100/a'; end
```

**Comment by yegor256** [comment]
@pnatashap maybe you can help with this?

**Comment by EugenDueck** [comment]
Meanwhile I have tried once more to replicate this stripped down version with Linux, but I wasn't able to. I tried > 1.3M times with OpenJDK 17.0.1, and >1M times with 11.0.22, and actually this time around I did it concurrently, due to reasons of patience, but I just cannot seem to get it to replicate on Linux (Ubuntu 22.04, 5.15.0-101-lowlatency #111-Ubuntu SMP PREEMPT)

**Comment by EugenDueck** [comment]
Another difference I should mention: The Windows machines are all virtual machines. Production is an AWS EC2, the other Windows machine runs on VirtualBox with a Linux host. The machines I were not able to replicate it on are all physical (x64 in the case of Linux and arm64 (Apple M2) in the case of Mac). Not sure this fact is relevant in this case, but some VMs have e.g. clock issues, so TSC time can jump backwards, which is but one thing differentiating virtual from physical machines.

**Comment by EugenDueck** [comment]
I just replicated the issue with the latest stable takes 1.24.4, on the same Windows machine, after 36k requests.

**Comment by EugenDueck** [comment]
Here's a really short version that still replicates the problem (again on Window; this time around, it took 35k attempts):
```java
    public static void main(String[] args) throws IOException {
        new FtBasic(new TkFork(new FkRegex("/a", "k")), 8100).start(Exit.NEVER);
    }
```

**Comment by EugenDueck** [comment]
@yegor256 
I still could only reproduce the bug in Windows, but if you use e.g. 6, 7 loops invoking curl in parallel, it always reproduces within 2, 3 seconds. When applying the PR, I could not reproduce it any longer.

**Comment by EugenDueck** [comment]
@yegor256 I guess there won't be an "official" hotfix for 1.19? (This is the version we are using in production)

**Comment by yegor256** [comment]
@EugenDueck yes, we don't do backporting in this project. We'll most probably fix this issue and then release 1.24.5. Is it a problem?

**Comment by EugenDueck** [comment]
@yegor256 Totally understand that.
The old version does not build on a recent JDK (I'm currently using 17 or newer), but I will get me an older JDK (8 or 11) and with that I'm pretty sure I'll get it to build, so I can create a hotfix myself. But thanks for asking!

**Comment by EugenDueck** [comment]
@yegor256 I have just added a regression test to the PR, which replicates the problem in an unfixed version.

**Comment by EugenDueck** [comment]
@baudoliver7 On what OS did this issue occur for you? Also, what JDK version? If you remember.

**Comment by baudoliver7** [comment]
@EugenDueck It occurs on Windows with JDK 8
