### ISSUE TITLE
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/cactoos/Scalar

### ISSUE THREAD

**Issue by friji350** [yegor256/takes#1339]
`$ java -Dfile.encoding=UTF-8 -cp takes.jar:. App
`

Error:
```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/cactoos/Scalar
        at org.takes.facets.fork.FkRegex.<init>(FkRegex.java:175)
        at org.takes.facets.fork.FkRegex.<init>(FkRegex.java:151)
        at org.takes.facets.fork.FkRegex.<init>(FkRegex.java:107)
        at App.main(App.java:7)
Caused by: java.lang.NoClassDefFoundError: org/cactoos/Scalar
        ... 4 more
Caused by: java.lang.ClassNotFoundException: org.cactoos.Scalar
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

```

**Comment by friji350** [comment]
@yegor256 Check it please

**Comment by yegor256** [comment]
@rultor release, tag is `1.24.6`

**Comment by yegor256** [comment]
@rultor release, tag is `1.24.6`

**Comment by yegor256** [comment]
@friji350 I fixed the README file, now it explains that you should use `takes-1.24.6-jar-with-dependencies.jar` I'm sure it will work. If not, open a new ticket please.
