### ISSUE TITLE
CcStrict should not touch urn() or anonymous identity

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#184]
`CcStrict` should not touch `urn()` or anonymous identity, because it leads to runtime exception:

```
java.lang.UnsupportedOperationException: #urn()
	at org.takes.facets.auth.Identity$1.urn(Identity.java:50)
	at org.takes.facets.auth.codecs.CcStrict.applyRules(CcStrict.java:67)
	at org.takes.facets.auth.codecs.CcStrict.decode(CcStrict.java:58)
	at org.takes.facets.auth.PsCookie.enter(PsCookie.java:104)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:72)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:76)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:45)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:57)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:56)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:89)
	at org.takes.http.BkBasic.accept(BkBasic.java:73)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkParallel$1.run(BkParallel.java:90)
```

**Comment by davvd** [comment]
@yegor256 I tagged this as "bug"

**Comment by davvd** [comment]
@cyberone this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-f31d7d37`

**Comment by cyberone** [comment]
@davvd please review https://github.com/yegor256/takes/pull/204

**Comment by cyberone** [comment]
@yegor256 the corresponding PR is merged. Close the task please.

**Comment by yegor256** [comment]
@cyberone thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@cyberone 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 56383385; I added **38 mins** to your account, many thanks for working with the project! The completion time here was 56383397.; there is a bonus for fast delivery (age=3243); +38 added to your rating, at the moment it is: [+158](http://www.netbout.com/b/35076?open=rating)
