### ISSUE TITLE
PsGoogle.fetch() cause JsonParsingException 

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#382]
PsGoogle.fetch() causes JsonParsingException 
see https://github.com/yegor256/netbout/issues/786

>javax.json.stream.JsonParsingException: Not Found
	at com.jcabi.http.response.JsonResponse$VerboseReader.readObject(JsonResponse.java:161)
	at org.takes.facets.auth.social.PsGoogle.fetch(PsGoogle.java:150)
	at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:108)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:84)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.forward.TkForward.act(TkForward.java:66)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.json.stream.JsonParsingException: Unexpected char 78 at (line no=1, column no=1, offset=0)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:415)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:222)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)

**Comment by dmzaytsev** [comment]
@yegor256 I guess the scope has not be set during the authorization code request. I think it is the reason

**Comment by davvd** [comment]
@dmzaytsev I will find a developer for the task soon...

**Comment by davvd** [comment]
@dmzaytsev since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@dmzaytsev thank you for the ticket reported, I topped your account for 15 mins, transaction `65338452`

**Comment by davvd** [comment]
@tiaped can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by tiaped** [comment]
@davvd I am not sure I can finish this task on time. Could you please find another developper

**Comment by davvd** [comment]
> @davvd I am not sure I can finish this task on time. Could you please find another developper.

@tiaped I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd I am not sure I can finish this task on time. Could you please find another developper.

@tiaped no problem, I will try to find somebody else

**Comment by davvd** [comment]
@dimonn12 can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmzaytsev** [comment]
@yegor256 @davvd it's already fixed.
yegor256/netbout#786 resolved
I'm closing the ticket

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@dimonn12 there weren't any messages from you, no need to pay, as I understand (feel free to correct me)
