### ISSUE TITLE
BkTimeableTest fails intermittently

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#506]
```./takes>mvn -o test```

Sometimes ```org.takes.http.BkTimeableTest``` fails and sometimes it passes. It should be fixed.

```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.746 sec - in org.takes.facets.auth.social.PsGoogleTest
Running org.takes.http.BkTimeableTest
Exception in thread "Thread-1" java.lang.IllegalStateException: java.io.FileNotFoundException: C:\Users\fatcat\AppData\Local\Temp\junit8691524069542580095\junit3177265002913825846.tmp (The system cannot find the path specified)
        at org.takes.http.BkTimeableTest$2.run(BkTimeableTest.java:96)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: C:\Users\fatcat\AppData\Local\Temp\junit8691524069542580095\junit3177265002913825846.tmp (The system cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at org.takes.http.Options.socket(Options.java:130)
        at org.takes.http.FtCLI.start(FtCLI.java:94)
        at org.takes.http.BkTimeableTest$2.run(BkTimeableTest.java:88)
        ... 1 more
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.513 sec <<< FAILURE! - in org.takes.http.BkTimeableTest
stopsLongRunningBack(org.takes.http.BkTimeableTest)  Time elapsed: 1.513 sec  <<< ERROR!
java.io.FileNotFoundException: File 'C:\Users\fatcat\AppData\Local\Temp\junit8691524069542580095\junit3177265002913825846.tmp' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
        at org.takes.http.BkTimeableTest.stopsLongRunningBack(BkTimeableTest.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Running org.takes.misc.VerboseIterableTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.takes.misc.VerboseIterableTest
Running org.takes.http.BkReuseTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 0 sec - in org.takes.http.BkReuseTest
Running org.takes.facets.auth.social.PsGithubTest
[?[0;37mINFO?[m] pool-1-thread-3 com.jcabi.http.request.BaseRequest: #fetch(POST localhost:57818 /login/oauth/access_token): [200 OK] in 16ms
[?[0;37mINFO?[m] pool-1-thread-3 com.jcabi.http.request.BaseRequest: #fetch(GET localhost:57818 /user): [200 OK] in 0ms
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.075 sec - in org.takes.facets.auth.social.PsGithubTest
Running org.takes.rs.RsJSONTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.331 sec - in org.takes.rs.RsJSONTest
Running org.takes.facets.auth.social.PsLinkedinTest
[?[0;37mINFO?[m] pool-1-thread-8 com.jcabi.http.request.BaseRequest: #fetch(POST localhost:57820 /uas/oauth2/accessToken): [200 OK] in 0ms
[?[0;37mINFO?[m] pool-1-thread-8 com.jcabi.http.request.BaseRequest: #fetch(GET localhost:57820 /v1/people/): [200 OK] in 0ms
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.216 sec - in org.takes.facets.auth.social.PsLinkedinTest
Running org.takes.rs.RsWithoutHeaderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.takes.rs.RsWithoutHeaderTest
Running org.takes.facets.auth.TkAuthTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.468 sec - in org.takes.facets.auth.TkAuthTest
Running org.takes.facets.auth.codecs.CcBase64Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in org.takes.facets.auth.codecs.CcBase64Test
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  BkTimeableTest.stopsLongRunningBack:104 -+ FileNotFound File 'C:\Users\fatcat\A...

Tests run: 302, Failures: 0, Errors: 1, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by davvd** [comment]
@simonjenga milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@rajithd can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@simonjenga many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `74654376`

**Comment by rajithd** [comment]
@simonjenga couldn't reproduce the issue. Tried many ways to reproduce (mvn -o test, mvn clean install, mvn test,  mvn -Dtest=BkTimeableTest test) but all the test cases were passed without any issue. I'm suspecting this may related to OS because I'm using Ubuntu and based on the log you are using windows. Is there any additional steps for this ?

**Comment by simonjenga** [comment]
@rajithd It may be related to the OS. I am using ```Windows 7``` and i just executed the command:
 ```mvn -Dtest=BkTimeableTest test``` and i was able to reproduced the same issue with the error again.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.takes.http.BkTimeableTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.83 sec <<< FAILURE! - in org.takes.http.BkTimeableTest
stopsLongRunningBack(org.takes.http.BkTimeableTest)  Time elapsed: 1.83 sec  <<< ERROR!
java.io.FileNotFoundException: File 'C:\Users\fatcat\AppData\Local\Temp\junit7823434478729757194\junit6511253519646324226.tmp' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
        at org.takes.http.BkTimeableTest.stopsLongRunningBack(BkTimeableTest.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  BkTimeableTest.stopsLongRunningBack:104 ┬╗ FileNotFound File 'C:\Users\fatcat\A...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by davvd** [comment]
@rajithd check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

added -30 to your rating, now it is equal to [-90](http://www.netbout.com/b/36278?open=rating)

**Comment by davvd** [comment]
@rajithd the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html); -60 added to your rating, current score is: [-240](http://www.netbout.com/b/36278?open=rating)

**Comment by davvd** [comment]
@raphaelln could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by raphaelln** [comment]
@simonjenga please could you please share with me your environment configs ? I couldn't reproduce the error, following my configs:

- Windows 7 Professional
- java 8 (1.8.0_51)
- maven 3.3.9
- intel core 2 duo 2.93 
- 8gb ram

Besides that, I investigated the source and I believe is the time to create the temp file is greater than in our machine than ours, because the test first create and delete the file:

`final File file = this.temp.newFile();`
 `file.delete();`

After that, starts the thread, which will create the socket connection and the required file.

But the sleep time (1500 ms) in the test case, is not enough to create the file in time to be able to process it in the next line of the code.

Please if possible, could you please put just for a little test, the following line in:

Options.java
after line 182 
`System.out.println("*************` CLOSING THE FILE ***********************");`

And try to simulate the error again, and please check if the above code is executed before the read try.

**Comment by simonjenga** [comment]
@raphaelln There are intermittent results (```FAILURE/SUCCESS```) within Unit tests that have something to do with creating files in the ```temp``` Dir in my computer.

```
System.out.println(System.getProperty("java.io.tmpdir"));
C:\Users\fatcat\AppData\Local\Temp\
```

Try to reproduce this issue in the following environment:

```
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jdk1.7.0_80\jre
Apache Maven >= 3.1.1
Default locale: en_GB, platform encoding: UTF-8
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
```

The same error messages may appear on: 
```Apache Maven 3.2.1```, ```Apache Maven 3.2.5``` and ```Apache Maven 3.3.3```

The reason this FAILURE sometimes happens is because this project generates and fills my ```temp``` Dir with a lot of folders and it does not delete them. I have to manually delete them to make the Build to pass.

I recently manually deleted all those folders in the my ```temp``` Dir and so far the Build is OK. But after some time, this problem will recur after executing the project Build several times for some days.

I think part of the fix to this issue is to visit the source code and look at places where ```temp``` folders are being created and not deleted e.g ```org.takes.tk.TkFilesTest.dispatchesByFileName()``` and then put appropriate code to delete the ```dir``` being created.

This is your request:
```
[INFO]
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ takes ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.takes.http.BkTimeableTest
************* CLOSING THE FILE ***********************
[←[0;37mINFO←[m] pool-1-thread-2 com.jcabi.http.request.BaseRequest: #fetch(GET localhost:49436 /): [200 OK] in 2s
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.05 sec - in org.takes.http.BkTimeableTest
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

https://github.com/teamed/qulice/issues/691

**Comment by raphaelln** [comment]
@davvd it's done in PR #601, please assign reviewer.

Thanks.

**Comment by davvd** [comment]
> @davvd it's done in PR #601, please assign reviewer.
> 
> Thanks.

@raphaelln OK, sure

**Comment by raphaelln** [comment]
@simonjenga PR #601 is merged. Please review and close the ticket if everything is ok.

Thanks.

**Comment by simonjenga** [comment]
@raphaelln I am reviewing it and I will close it shortly...

**Comment by simonjenga** [comment]
@raphaelln The fix has made this issue to disappear. I will open another issue if i come across similar problems related to creating ```temp``` files.
:thumbsup: :ok:

**Comment by raphaelln** [comment]
@davvd the issue was closed, please could you proceed.
thanks.

**Comment by davvd** [comment]
> @davvd the issue was closed, could you proceed please.
> thanks.

@raphaelln you are welcome

**Comment by raphaelln** [comment]
@davvd can you calculate this task?

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
@raphaelln added 10 mins to @elenavolokhova, for QA review, payment code is `78665675`

thanks, I just added **30 mins** to your account, payment `AP-09B27035W7591761S`, 404 hours and 9 mins spent

+30 to your rating, your total score is [+0](http://www.netbout.com/b/36530?open=rating)
