### ISSUE TITLE
NPE in PsByFlag

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#60]
```
java.lang.NullPointerException
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:104)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:71)
	at org.takes.facets.auth.TsAuth.route(TsAuth.java:87)
	at org.takes.ts.TsWrap.route(TsWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:89)
	at org.takes.http.BkBasic.accept(BkBasic.java:73)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkParallel$1.run(BkParallel.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.1`
