### ISSUE TITLE
RqMultipart throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#61]
```
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:3212)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1211)
	at xxxxxx.act(TkWrite.java:75)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.2`
