### ISSUE TITLE
Travis fails with a PDD error of type ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#718]
The build fails on travis due to:

```
INFO: "reading src/site/resources/logo.png..."
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/lib/pdd/source.rb:144:in `rescue in puzzles': ["in /home/travis/build/yegor256/takes/src/site/resources/logo.png", #<PDD::Error: ["in line #0", #<ArgumentError: invalid byte sequence in UTF-8>]>] (PDD::Error)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/lib/pdd/source.rb:142:in `puzzles'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/lib/pdd.rb:98:in `block (3 levels) in xml'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/lib/pdd.rb:97:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/lib/pdd.rb:97:in `block (2 levels) in xml'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/builder.rb:391:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/lib/pdd.rb:96:in `block in xml'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/builder.rb:293:in `initialize'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/lib/pdd.rb:94:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/lib/pdd.rb:94:in `xml'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/pdd-0.17.1/bin/pdd:91:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/pdd:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/pdd:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

The goal of this ticket is to find the root cause and fix it.

Here is a build failure for [more details](https://travis-ci.org/yegor256/takes/jobs/183940836).

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@essobedo fixed already, thanks
