### ISSUE TITLE
Version mismatch between pom and release

### ISSUE THREAD

**Issue by semantosoph** [yegor256/takes#741]
While the currently released version is 1.4, the pom still hinges at 1.1-SNAPSHOT. These values should under all circumstances be identical.

Please update the version manually for once and include an automatic process of updating the version number into the release process.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@semantosoph well, Maven recommends to keep `SNAPSHOT` version in the repository, while more stable versions get releases to Maven Central. We can't keep 1.4 in `master` branch, since we're changing it all the time. See https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401

**Comment by semantosoph** [comment]
@yegor256 Mhm. Would still need to be 1.4-SNAPSHOT in pom, wouldn't it?

**Comment by yegor256** [comment]
@semantosoph no, it has to be something from the future. In our case it has to be `2.0-SNAPSHOT`. Let me fix it.

**Comment by yegor256** [comment]
@semantosoph fixed in e4cd3e4d6

**Comment by semantosoph** [comment]
Fine. Working towards a new major version feels good anyway. :smile:

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
0.15.2 96d4c0a 2017-07-30T06:58:34
java.io.IOException: java.lang.IllegalArgumentException: There are 1 parameter(s) but only 0 format argument(s) were provided.
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at com.zerocracy.farm.SmartFarm.lambda$null$4(SmartFarm.java:137)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRu...
```
