### ISSUE TITLE
XeWhen must accept the third argument

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#758]
`XeWhen` should accept three arguments: the condition, the position scenario, the negative scenario. At the moment it's only one path.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#758` is now in scope, role is `DEV`.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+6645](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/758#issuecomment-356026016))

@yegor256 I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT c1bed0a7 2018-01-08T15:29:04
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/impediments/register_impediment.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/impediments/register_impediment.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:87)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.lambda$apply...
```

Cc @yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#758` assigned to @neonailol  ([profile](http://www.0crat.com/u/neonailol})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment]
@yegor256, PR #759 Was merged, issue can be closed

**Comment by yegor256** [comment]
@rultor release, tag is `1.8`

**Comment by 0crat** [comment]
The job [#758](https://github.com/yegor256/takes/issues/758) is now out of scope

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to [@neonailol](http://www.0crat.com/u/neonailol), total is [+60](http://www.0crat.com/u/neonailol)
