### ISSUE TITLE
ArrayIndexOutOfBoundsException in CcSalted

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#822]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.takes.facets.auth.codecs.CcSalted.unsalt(CcSalted.java:124)
	at org.takes.facets.auth.codecs.CcSalted.decode(CcSalted.java:70)
	at org.takes.facets.auth.codecs.CcAes.decode(CcAes.java:103)
	at org.takes.facets.auth.codecs.CcHex.decode(CcHex.java:117)
	at org.takes.facets.auth.codecs.CcSafe.decode(CcSafe.java:64)
	at com.zerocracy.tk.CcSecure.decode(CcSecure.java:77)
	at org.takes.facets.auth.PsCookie.enter(PsCookie.java:104)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.7`

**Comment by yegor256** [comment]
@rultor release, tag is `1.8.7`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
