### ISSUE TITLE
PsFacebook seems not to support UTF8 content

### ISSUE THREAD

**Issue by victornoel** [yegor256/takes#876]
Since PsFacebookTest relies on a random id to do its test, sometimes it retrieves UTF8 content which can't be parsed by Takes and/or restfb:
```
canLogin(org.takes.facets.auth.social.PsFacebookTest)  Time elapsed: 0.056 sec  <<< ERROR!
java.lang.IllegalArgumentException: com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '{"id":"JD6U6vubd1","name":"ⲉ鯨ɯ摓㻦恛҉祐፲"}'.
	at org.takes.facets.auth.social.PsFacebook.fetch(PsFacebook.java:199)
	at org.takes.facets.auth.social.PsFacebook.enter(PsFacebook.java:157)
	at org.takes.facets.auth.social.PsFacebookTest.canLogin(PsFacebookTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.restfb.exception.FacebookJsonMappingException: Unable to map JSON to Java. Offending JSON is '{"id":"JD6U6vubd1","name":"ⲉ鯨ɯ摓㻦恛҉祐፲"}'.
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:333)
	at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:408)
	at org.takes.facets.auth.social.PsFacebook.fetch(PsFacebook.java:195)
	... 20 more
Caused by: com.restfb.json.ParseException: Expected valid string character at 1:35
	at com.restfb.json.JsonParser.error(JsonParser.java:370)
	at com.restfb.json.JsonParser.expected(JsonParser.java:363)
	at com.restfb.json.JsonParser.readStringInternal(JsonParser.java:199)
	at com.restfb.json.JsonParser.readString(JsonParser.java:187)
	at com.restfb.json.JsonParser.readValue(JsonParser.java:84)
	at com.restfb.json.JsonParser.readObject(JsonParser.java:139)
	at com.restfb.json.JsonParser.readValue(JsonParser.java:88)
	at com.restfb.json.JsonParser.parse(JsonParser.java:67)
	at com.restfb.json.Json.parse(Json.java:289)
	at com.restfb.DefaultJsonMapper.toJavaObject(DefaultJsonMapper.java:263)
	... 22 more
```

I think Takes should be improved to be able to parse such content. So the test shouldn't simply be modified to pass, more tests should be added and the behaviour fixed.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#876](https://github.com/yegor256/takes/issues/876) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/34546e02-5056-4eb3-8e64-3363254d4761); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for review of PR #885

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #885  ([here](https://github.com/yegor256/takes/issues/876#issuecomment-445205768))

@krzyk The impediment for [#876](https://github.com/yegor256/takes/issues/876) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@victornoel Fix has been merged in #885, please close this issue

**Comment by victornoel** [comment]
@krzyk thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#876](https://github.com/yegor256/takes/issues/876) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/876#issuecomment-446752524))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/876#issuecomment-446752524))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by krzyk** [comment]
@paulodamaso error with funds here? If the estimate was when the project had funds it should pay them also after completion.

**Comment by paulodamaso** [comment]
@krzyk Looks like QA and REV jobs does not enter on estimates. But in this case I think that you've been assigned before we ran out of funds.

**Comment by krzyk** [comment]
@paulodamaso OK, I assume so

**Comment by paulodamaso** [comment]
@krzyk Have you been paid for this one?

**Comment by krzyk** [comment]
@paulodamaso I don't know :)
The only way to check that is to look at the user page, but 0crat did patyment already, and in paypal comment there is no mention of the issue number :(
