### ISSUE TITLE
Takes is not compatible with latest cacctoos dependency

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#978]
If I use the latest Takes version `v1.16` with latest Cactoos  version `v0.41`, Takes is crashing on `CcPlain` with stacktrace:
```
java.lang.NoClassDefFoundError: org/cactoos/text/SplitText
	at org.takes.facets.auth.codecs.CcPlain.decode(CcPlain.java:70)
	at org.takes.facets.auth.RqAuth.identity(RqAuth.java:78)
	at com.g4s8.test.TkApp.lambda$new$0(TkApp.java:67)
	at org.takes.facets.fork.FkParams.route(FkParams.java:91)
	at org.takes.facets.fork.FkChain.route(FkChain.java:73)
	at org.takes.facets.fork.TkFork.act(TkFork.java:98)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:208)
	at org.takes.facets.fork.FkChain.route(FkChain.java:73)
	at org.takes.facets.fork.TkFork.act(TkFork.java:98)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:107)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:87)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:56)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkGreedy$1.act(TkGreedy.java:54)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:127)
	at org.takes.http.BkBasic.accept(BkBasic.java:103)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:49)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:87)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.cactoos.text.SplitText
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/978#issuecomment-494788656))

@paulodamaso Job [#978](https://github.com/yegor256/takes/issues/978) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#978](https://github.com/yegor256/takes/issues/978) assigned to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/ad5a314f-b902-45a8-bd8f-bc44948858b7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
Fixed: `CcPlain` uses `org.cactoos.text.Split`, and Takes tracks current Cactoos releases.
